---
services:
  YT-HOME:
    image: ghcr.io/ytjungle666/yt-home:latest
    platform: linux/amd64
    container_name: yt-home
    hostname: "yt-home"
    volumes:
      - "./db:/app/db"
      - "./cert:/app/cert"
    tty: true
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "80:80"
      - "2096:2096"
    networks:
      - YT-HOME

networks:
  YT-HOME:
    driver: bridge
